// src/old/PackCard.svelte
<script>
    import Icon from 'svelte-awesome';
    import { refresh, check, download } from 'svelte-awesome/icons';
    export let pack;
</script>

<div class='card'>
    <div>
        <div class='pic'>
            <img src={pack.icon} alt='{pack.name} のアイコン'>
        </div>
        <div class='title'>
            <span><b>{pack.name}</b></span>
            <span>{pack.description}</span>
        </div>
    </div>
    <div>
        <div class='details'>
            <span>
                <Icon data={refresh}/>
                <span class='with-icon'>{pack.last_updated}</span>
            </span>
            <span>
                <Icon data={check}/>
                <span class='with-icon'>{pack.supported}</span>
            </span>
        </div>
        <div class='download'>
            <span>
                <Icon data={download}/>
                <a href={pack.download_url} class='with-icon'>ダウンロード</a>
            </span>
        </div>
    </div>
</div>

// src/components/PackCard.tsx
import { PackCardProps } from "../types/PackCardProps"
import CachedIcon from '@mui/icons-material/Cached'
import CheckIcon from '@mui/icons-material/Check'
import DownloadIcon from '@mui/icons-material/Download'
import "./PackCard.css"

export const PackCard: React.FC<{props: PackCardProps}> = ({props}) => {
    return (<div className='card'>
        <div>
            <div className='pic'>
                <img src={props.icon} alt={`${props.name}のアイコン`} />
            </div>
            <div className='title'>
                <span><b>{props.name}</b></span>
                <span>{props.description}</span>
            </div>
        </div>
        <div>
            <div className='details'>
                <span>
                    <CachedIcon />
                    <span className='with-icon'>{props.last_updated}</span>
                </span>
                <span>
                    <CheckIcon />
                    <span className='with-icon'>{props.supported}</span>
                </span>
            </div>
            <div className='download'>
                <span>
                    <DownloadIcon />
                    <a href={props.download_url} className='with-icon'>ダウンロード</a>
                </span>
            </div>
        </div>
    </div>)
}
